# name: Deploy to Azure App Service

# on:
#   workflow_run:
#     workflows: ["Docker Build & Push"]
#     types:
#       - completed

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}

#     steps:
#       - name: Azure Login
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

#       - name: Deploy Docs
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: devcentral-docs
#           images: devcentralacr.azurecr.io/devcentral-docs:latest

#       - name: Deploy Web
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: devcentral-web
#           images: devcentralacr.azurecr.io/devcentral-web:latest
